/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-fab-menu-item.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../paper-fab/paper-fab.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />

declare namespace UiElements {

  /**
   * The `<paper-fab-menu-item>` is a menu item that can be used with `<paper-fab-menu>`.
   *
   * It renders as a mini fab button but it's hidden. The `<paper-fab-menu>` triggers menu items when hovered.
   *
   * See `<paper-fab-menu>` for more information and demos.
   */
  class PaperFabMenuItem extends Polymer.Element {

    /**
     * Color of the menu item.
     */
    color: string|null|undefined;

    /**
     * The delay (in ms) before the entry / exit animation begins.
     */
    transitionDelay: number|null|undefined;

    /**
     * Label only used with paper-fab when the icon is not present.
     */
    label: string|null|undefined;

    /**
     * The icon to render. It's binded to `paper-fab`'s icon property.
     */
    icon: string|null|undefined;

    /**
     * If true this item will be rendered as opened.
     * This property is used by the `paper-fab-menu` element to determine
     * control state. Do not use this property.
     */
    opened: boolean|null|undefined;
    _updateTransitionDelay(transitionDelay: any): void;

    /**
     * Called when color has changed.
     */
    _colorChanged(color: any): void;
    _computeMainClass(opened: any): any;
  }
}

interface HTMLElementTagNameMap {
  "paper-fab-menu-item": UiElements.PaperFabMenuItem;
}
